# Generated by Django 4.1.1 on 2022-10-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='tanggal_lahir',
            new_name='jabatan',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='alamat',
        ),
    ]
